# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='lawyered/media/'),
        ),
    ]
